server:
  port: 8080

spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/today-assemble
    username: ${dbUserName}
    password: ${dbPassword}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          timeout: 5000
          starttls:
            enable: true


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace